version: '3.8'

services:
  mroi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DB_HOST=192.168.100.83
      - DB_PORT=5432
      - DB_DATABASE=ivs_service
      - DB_USER=aiintern
      - DB_PASSWORD=Public@aiintern0
      - DB_NAME=mroi_db
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#      - /app/node_modules

#volumes:
#  ffmpeg_cache: